upload 2.1,60bb66794a21b,sync cvi_comm_vdec.h
Change-Id: If0e148fccbfbd9444c383138edfcdd4f9116a151

diff --git a/v2/modules/bin/Makefile b/v2/modules/bin/Makefile
--- a/v2/modules/bin/Makefile
+++ b/v2/modules/bin/Makefile
@@ -1,7 +1,7 @@
 SHELL = /bin/bash
 ifeq ($(PARAM_FILE), )
-     PARAM_FILE:=../../Makefile.param
-     include $(PARAM_FILE)
+	PARAM_FILE:=../../Makefile.param
+	include $(PARAM_FILE)
 endif
 
 SDIR = $(PWD)/src
@@ -10,7 +10,6 @@ HDIR = $(PWD)/include
 TMP_FOLDER = $(PWD)/tmp
 
 INDEX_STRATEGY = 1
-ARFLAGS_x = x
 
 INCS = -I$(MW_INC) -I$(MOD_INC) -I$(SYS_INC) -I$(ISP_INC) -Iinclude
 INCS += -I$(MW_PATH)/modules/vpss/include -I../isp/algo
@@ -21,6 +20,19 @@ PARAM_SRC = $(HDIR)/cvi_bin_param_header.h
 PARAM_PRE = $(addsuffix .i,$(basename $(addprefix $(TMP_FOLDER)/,$(notdir $(PARAM_SRC)))))
 PARAM_DEP = $(addsuffix .d,$(basename $(addprefix $(TMP_FOLDER)/,$(notdir $(PARAM_SRC)))))
 
+isp_chip_dir := $(shell echo $(CHIP_ARCH) | tr A-Z a-z)
+
+PROFILE_ISP = ../isp/common/toolJsonGenerator/$(isp_chip_dir)/cvi_bin_profile.json
+PROFILE_CVI_BIN = python/cvi_bin_profile.json
+
+check_isp_profile_ret := $(shell test -f "$(PROFILE_ISP)"; echo $$?)
+
+ifeq ($(check_isp_profile_ret), 0)
+	PROFILE := $(PROFILE_ISP)
+else
+	PROFILE := $(PROFILE_CVI_BIN)
+endif
+
 TARGET_A = $(MW_LIB)/libcvi_bin.a
 TARGET_SO = $(MW_LIB)/libcvi_bin.so
 
@@ -30,15 +42,25 @@ ifeq ($(MULTI_PROCESS_SUPPORT), 1)
 EXTRA_CFLAGS += -DRPC_MULTI_PROCESS
 endif
 
-EXTRA_CFLAGS += -DISP_BIN_COMMIT=\"$(shell git rev-parse --short HEAD)\"
-gerrit_id=$(shell git log -n1 | grep Reviewed-on | tail -n1 | sed "s/.*+\///g")
+check_git_repo_ret := $(shell git log &>/dev/null; echo $$?)
+
+ifeq ($(check_git_repo_ret), 0)
+	commit_id = $(shell git rev-parse --short HEAD | cut -c1-9)
+	gerrit_id = $(shell git log -n1 | grep Change-Id | tail -n1 | sed -n 's/.*Change-Id: \(.*\)/\1/;s/\(.\{16\}\).*/\1/p')
+endif
+
+ifneq ($(commit_id), )
+	EXTRA_CFLAGS += -DISP_BIN_COMMIT=\"$(commit_id)\"
+endif
+
 ifneq ($(gerrit_id), )
 	EXTRA_CFLAGS += -DISP_BIN_GERRIT=\"$(gerrit_id)\"
 endif
 
-.PHONY : clean all cleanall gencode
+.PHONY : clean all gencode check
+
 all : gencode
-target : $(TARGET_A) $(TARGET_SO)
+target : check $(TARGET_A) $(TARGET_SO)
 
 gencode: $(PARAM_PRE)
 
@@ -46,22 +68,21 @@ $(TMP_FOLDER):
 	@echo "Create $(TMP_FOLDER) for object file"
 	-@mkdir -p $(TMP_FOLDER)
 
-$(PARAM_PRE): $(PARAM_SRC) | $(TMP_FOLDER)
+$(PARAM_PRE): $(PARAM_SRC) $(SRCS) | $(TMP_FOLDER)
 ifeq ($(INDEX_STRATEGY),1)
 	@$(CC) -E $(DEPFLAGS) $(EXTRA_CFLAGS) -c $< -o $@
 	@sed -i '1s|.*|$@: \\|' $(PARAM_DEP)
 	@echo "Generate code"
-	@python3 python/gencode.py $@
+	@python3 python/gencode.py $@ --profile $(PROFILE)
+ifeq ($(check_isp_profile_ret), 0)
+	@cp -f $(PROFILE_ISP) $(PROFILE_CVI_BIN)
 endif
-	$(MAKE) target
+endif
+	@$(MAKE) target
 
-result = $(shell ./CalPqBinMD5.sh)
-ifeq ($(result),-1)
-abort:
-	@echo $(result)
-	$(error "md5 error: please check CalPqBinMD5.sh")
-else
-	EXTRA_CFLAGS += -DISP_BIN_MD5=\"$(result)\"
+md5_result = $(shell ./CalPqBinMD5.sh)
+ifneq ($(md5_result), -1)
+	EXTRA_CFLAGS += -DISP_BIN_MD5=\"$(md5_result)\"
 endif
 
 ifeq ($(INDEX_STRATEGY),1)
@@ -86,14 +107,30 @@ $(TARGET_SO): $(OBJS)
 	@echo -e $(GREEN)[LINK]$(END)[$(notdir $(LD))] $(notdir $(TARGET_SO))
 	@$(STRIP) $(TARGET_SO)
 
+check:
+	@echo ">>>>>> check start"
+	@echo "profile: $(PROFILE)"
+	@if [ "$(check_git_repo_ret)" == "0" ]; then \
+		echo "git repo: Yes"; \
+		echo "commit_id: $(commit_id)"; \
+		echo "gerrit_id: $(gerrit_id)"; \
+	else \
+		echo "git repo: No"; \
+	fi
+	@echo "md5 value: $(md5_result)"
+	@if [ "$(md5_result)" == "-1" ]; then \
+		echo "Error: md5 is -1, please check the the md5!"; \
+		exit 1; \
+	fi
+	@echo "<<<<<< check end"
+
 clean:
 	@rm -f $(OBJS) $(DEPS) $(TARGET_A) $(TARGET_SO)
 	@rm -f $(PARAM_DEP) $(PARAM_PRE)
 	@rm -f $(SDIR)/*.autogen.*
 	@rm -f $(HDIR)/*.autogen.*
-
-cleanall: clean
 	@rm -rf $(TMP_FOLDER)
+	@rm -f python/cvi_bin_struct.h
 
 -include $(DEPS)
 -include $(PARAM_DEP)
